### ISSUE TITLE
Consider passing the configuration to the log_context from config file

### ISSUE THREAD

**Issue by ThomasDelteil** [msalvaris/gpu_monitor#10]
`with log_context('localhost', 'admin', 'password', 'gpudb', 'gpuseries'):`
This exposes username and password in plain text in the code.

**Comment by msalvaris** [comment]
Good idea

**Comment by ThomasDelteil** [comment]
@msalvaris what is the correct usage after this PR if we want to use the .env ?

**Comment by msalvaris** [comment]
@ThomasDelteil  .env file in the same directory as you are executing the cli logger or the logging context and the necessary information will be pulled from it. It uses python-dotenv find_dotenv which will search higher folders in the hierarchy as well ([https://github.com/theskumar/python-dotenv/blob/master/dotenv/main.py](https://github.com/theskumar/python-dotenv/blob/master/dotenv/main.py)) Let me know if you run into any issues.
