### ISSUE TITLE
[Feature Request] Logging CPU utilization as well

### ISSUE THREAD

**Issue by ThomasDelteil** [msalvaris/gpu_monitor#11]
Since the GPU performance is often tied to CPU utilization especially in data augmentation heavy pipeline, it could be nice to pass the CPU utilization data as well to be able to visualize it in a single consolidated dashboard.

**Comment by msalvaris** [comment]
Hm, yea network and disk utilization were also on my mind. Might simply create a new tool.

**Comment by msalvaris** [comment]
Closing since I think it is out of scope for this monitoring tool
